### ISSUE TITLE
Maintaining the provider

### ISSUE THREAD

**Issue by dahendel** [mauromedda/terraform-provider-awx#3]
Are you still maintaining or working on the provider? I have a lot of work I have done for it like upgrading it for terraform 0.12, started adding a few more resources, data resources, nested groups in inventory_groups, passing extra credential id's in job template, and much more. The upgrade to 0.12 involved converting to go modules. I also have a fork of the awx-go sdk that I have been working on pretty heavily. I would be more than happy to clean everything up and provide a PR, or I am happy to maintain the fork(s) if you are no longer working on the project. We use it heavily at my current company.

Thanks!

**Comment by MichaelPak** [comment]
@dahendel, I also need this provider in my company. We have about 200 jobs and workflows and it's really difficult to maintain it all manually. Can you update your fork? I would love to work on it with you.

**Comment by dahendel** [comment]
@MichaelPak I have made github.com/dahendel/terraform-provider-awx2 since I updated for terraform 0.12. Also, I have been working on a provisioner, github.com/dahendel/terraform-provisioner-awx, if you are interested. I have some changes/bugfixes to push, but we are using the provisioner pretty consistently.

**Comment by MichaelPak** [comment]
@dahendel thanks, I'll fork your project. And I hope @mauromedda will return to us.

**Comment by dahendel** [comment]
I am going to be maintaining github.com/dahendel/terraform-provider-awx2
